"""
Student information for this assignment:

On my/our honor, Cesar Monagas and Helen Moon,this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: cam9225
UT EID 2: ym8729
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    use_it = group_sum(start + 1, nums, target - nums[start])
    skip_it = group_sum(start + 1, nums, target)
    return use_it or skip_it


def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] == 6:
        return group_sum_6(start + 1, nums, target - 6)
    return (group_sum_6(start + 1, nums, target - nums[start]) or
            group_sum_6(start + 1, nums, target))


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    use_and_skip_next = group_no_adj(start + 2, nums, target - nums[start])
    skip_this = group_no_adj(start + 1, nums, target)
    return use_and_skip_next or skip_this


def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    curr = nums[start]
    if curr % 5 == 0:
        if start + 1 < len(nums) and nums[start + 1] == 1:
            return group_sum_5(start + 2, nums, target - curr)
        return group_sum_5(start + 1, nums, target - curr)
    if start > 0 and curr == 1 and nums[start - 1] % 5 == 0:
        return group_sum_5(start + 1, nums, target)
    return (group_sum_5(start + 1, nums, target - curr) or
            group_sum_5(start + 1, nums, target))


def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    same = 1
    total = nums[start]
    pos = start
    while pos + 1 < len(nums) and nums[pos + 1] == nums[start]:
        same += 1
        total += nums[start]
        pos += 1
    return (group_sum_clump(start + same, nums, target - total) or
            group_sum_clump(start + same, nums, target))


def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if not nums:
        return True
    def helper(pos, first, second):
        if pos >= len(nums):
            return first == second
        if helper(pos + 1, first + nums[pos], second):
            return True
        if helper(pos + 1, first, second + nums[pos]):
            return True
        return False
    return helper(0, 0, 0)


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if not nums:
        return False
    def helper(pos, odd, tens):
        if pos >= len(nums):
            return odd % 2 == 1 and tens % 10 == 0
        curr = nums[pos]
        if helper(pos + 1, odd + curr, tens):
            return True
        if helper(pos + 1, odd, tens + curr):
            return True
        return False
    return helper(0, 0, 0)


def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if not nums:
        return True
    def helper(pos, group5, group3):
        if pos >= len(nums):
            return group5 == group3
        n = nums[pos]
        if n % 5 == 0:
            return helper(pos + 1, group5 + n, group3)
        if n % 3 == 0:
            return helper(pos + 1, group5, group3 + n)
        return (helper(pos + 1, group5 + n, group3) or
                helper(pos + 1, group5, group3 + n))
    return helper(0, 0, 0)
